In [187]:
import numpy as np
import itertools
from itertools import chain, combinations


In [2]:
def generate_data(nrows, ncols):
    return np.random.randint(low=0, high=2, size=(nrows, ncols))
    

In [4]:
generate_data(10,5)

array([[1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 0, 0, 0]])

In [52]:
def findsubsets(S,m):
    '''finds subsets of S of size m'''
    return list(itertools.combinations(S, m))

In [159]:
def powerset(seq):
    """
    Returns all the subsets of this set. This is a generator.
    """
    if len(seq) <= 1:
        yield seq
        yield []
    else:
        for item in powerset(seq[1:]):
            yield [seq[0]]+item
            yield item

In [204]:
def count_distinct(index_list, data):
    '''index_list must be a list or array in {0,...,d}'''
    A = data
    print("Number unique items in A: {}".format(len(np.unique(A, axis=0))))
    #print(A)
    n,d = A.shape
    T = index_list
    
    if len(T) > d: # catch error when T is too large
        raise ValueError("T is {} but must be at most {}".format(len(T),d))
    subsets = powerset(T) 
    for subcube in powerset(T):
        if subcube != []:
            print("subcube {}".format(subcube))
            A_subcube = A[:,subcube]
            print("Number unique items: {}".format(len(np.unique(A_subcube, axis=0))))
            print("Unique items: {}".format(np.unique(A_subcube, axis=0)))
           

In [208]:
count_distinct([0,1,2,3,4], generate_data(10,5))

Number unique items in A: 10
[[1 0 0 1 1]
 [1 1 0 0 0]
 [0 0 0 1 1]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [0 0 0 0 1]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [1 1 0 1 1]
 [0 0 1 0 1]]
subcube [0, 1, 2, 3, 4]
Number unique items: 10
Unique items: [[0 0 0 0 1]
 [0 0 0 1 1]
 [0 0 1 0 1]
 [0 1 0 0 0]
 [0 1 1 1 0]
 [1 0 0 1 1]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [1 1 0 0 0]
 [1 1 0 1 1]]
subcube [1, 2, 3, 4]
Number unique items: 8
Unique items: [[0 0 0 1]
 [0 0 1 1]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 1 1]
 [1 1 1 0]]
subcube [0, 2, 3, 4]
Number unique items: 9
Unique items: [[0 0 0 0]
 [0 0 0 1]
 [0 0 1 1]
 [0 1 0 1]
 [0 1 1 0]
 [1 0 0 0]
 [1 0 1 1]
 [1 1 1 0]
 [1 1 1 1]]
subcube [2, 3, 4]
Number unique items: 6
Unique items: [[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
subcube [0, 1, 3, 4]
Number unique items: 8
Unique items: [[0 0 0 1]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 1 0]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 1 1]]
subcube [1, 3, 4]
Number unique items: 6
Unique items: [[0 0 1]
 [0 1 0]
 [0 1 1]
 [1

In [53]:
x = findsubsets([1,2,3], 2)

In [54]:
x[0]

(1, 2)

In [158]:
for i in powerset([1,2,3]):
    print(i)

[1, 2, 3]
[2, 3]
[1, 3]
[3]
[1, 2]
[2]
[1]
[]
